input {
  tcp {
    port => 5044
    codec => json
  }
}

# We remove the empty filter block to avoid the "Missing Filter End Vertex" error
output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "user-service-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}