# Server
server.port=8090
spring.application.name=DOCKER-DEMO
server.servlet.context-path=/demo

# Redis - Ubuntu machine IP
spring.data.redis.host=172.24.204.45
spring.data.redis.port=6379
spring.cache.type=redis

# Elasticsearch - Ubuntu machine IP
spring.elasticsearch.uris=http://172.24.204.45:9200