name: Native CI-CD to Nexus

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Targets your local PC runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        # Using the exact path to mvn.cmd from your local environment
        run: |
          & "C:\Users\heg\.m2\wrapper\dists\apache-maven-3.9.12\59fe215c0ad6947fea90184bf7add084544567b927287592651fda3782e0e798\bin\mvn.cmd" clean package -DskipTests

      - name: Deploy to Native Nexus
        # This pushes your demo.war to localhost:8081
        run: |
          & "C:\Users\heg\.m2\wrapper\dists\apache-maven-3.9.12\59fe215c0ad6947fea90184bf7add084544567b927287592651fda3782e0e798\bin\mvn.cmd" deploy -DskipTests.cmd" clean package -DskipTests

      - name: Deploy to Native Nexus
        # This pushes your demo.war (0.0.1-SNAPSHOT) to localhost:8081
        run: |
          & "C:\Users\heg\.m2\wrapper\dists\apache-maven-3.9.12\59fe215c0ad6947fea90184bf7add084544567b927287592651fda3782e0e798\bin\mvn.cmd" deploy -DskipTests